#security:
#  basic:
#    enabled: false
#management:
#  security:
#    enabled: false
security:
  user:
    password: password
server:
  port: 9000
domain:
  hourlyCost:
    client: 125
    internal: 65